### ISSUE TITLE
sockshandler error executing weevely

### ISSUE THREAD

**Issue by ajcborges** [epinna/Weevely#60]
[+] weevely 3.2.0
[!] Error: too few arguments

[+] Run terminal to the target
    weevely <URL> <password> [cmd]

[+] Load session file
    weevely session <path> [cmd]

[+] Generate backdoor agent
    weevely generate <password> <path>

root@kali2:~# 

root@kali2:~# weevely http://www.site.com/Blogs/404.php magic
Traceback (most recent call last):
  File "./weevely.py", line 98, in <module>
    main(arguments)
  File "./weevely.py", line 48, in main
    modules.load_modules(session)
  File "/usr/share/weevely/core/modules.py", line 24, in load_modules
    (module_group, module_name), fromlist=["*"]
  File "/usr/share/weevely/modules/shell/php.py", line 4, in <module>
    from core.channels.channel import Channel
  File "/usr/share/weevely/core/channels/channel.py", line 8, in <module>
    import sockshandler
ImportError: No module named sockshandler
root@kali2:~#

**Comment by epinna** [comment]
You didn't install the library dependencies as PySocks. Please follow the installing tutorial here:

https://github.com/epinna/weevely3/wiki/Install-and-first-run
